version: '3'
services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}

  backend:
     build: ./backend
     ports:
       - '80:80'
     depends_on:
       - postgres

  frontend:
    build: ./frontend
    ports:
        - '3000:3000'
    volumes:
        - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
