version: '3'
services:
  mongo:
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - alumni-app-network
    volumes:
      - data:/data/db

  strapi:
    image: strapi/strapi
    env_file: 
      - .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - alumni-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
        - '3000:3000'
    volumes:
        - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - strapi

networks:
  alumni-app-network:
    driver: bridge

volumes:
  data:
